name: Build Binaries

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build binary
        run: |
          mkdir -p dist
          EXT=""
          if [ "${{ matrix.goos }}" = "windows" ]; then
            EXT=".exe"
          fi
          OUTPUT="dist/goproxy_${{ matrix.goos }}_${{ matrix.goarch }}${EXT}"
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o "$OUTPUT" .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: goproxy-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/
